[project]
name = "stdn-agentic"
version = "0.1.0"

[project.scripts]
stdn = "stdn_agentic.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.12.2",
    "pydantic-ai>=0.0.14",
    "ollama>=0.3.0",
    "pandas>=2.0.0",
    "asyncio",
    "argparse",
    "dataclasses",
    "typing-extensions"
]
